#ifndef __IOGROUP_BASE_HPP
#define __IOGROUP_BASE_HPP

#include <stdint.h>
#include <libconfig.h++>
#include <dbus-c++/dbus.h>
#include <boost/signals2.hpp>
#include "exception/baseexceptions.hpp"
#include "log/log.hpp"
#include "pi-io-server-glue.hpp"
#include "gpioregistry.hpp"

DefineNewMsgException(FeatureNotImplementedException);
DefineNewMsgException(IoPinInvalidException);
DefineNewMsgException(ConfigInvalidException);

class IoGroupBase : public nl::miqra::PiIo::IoGroup_adaptor, // << This will be generated by the makefile using dbusxx-xml2cpp on pi-io-introspect.xml
  public DBus::IntrospectableAdaptor,
  public DBus::ObjectAdaptor
{
public:

    IoGroupBase(DBus::Connection &connection,std::string &dbuspath, GpioRegistry &registry);
    virtual ~IoGroupBase();
    
    virtual void Initialize(libconfig::Setting &setting);

    // Return the name of this iogroup
    std::string Name();
    
    void Name(std::string s);
    
    // Return the dbus path of the group
    DBus::Path Path();
    
    // Return the name of the interface used in this group
    virtual std::string Interface(){ return "nl.miqra.PiIo.IoGroup"; }

    boost::signals2::signal<void (IoGroupBase *, std::string)> onCriticalError;

protected:
    GpioRegistry &gpioRegistry;

private:
    std::string name;
    DBus::Path path;
};

#endif//__IOGROUP_BASE_HPP
